ghkdqhrbals/spring-chatting-server

- docker-compose-only-chat.yaml
- spring-chatting-backend-server/build.gradle
- spring-chatting-backend-server/src/main/java/chatting/chat/config/EurekaConfig.java
- spring-chatting-backend-server/src/main/java/chatting/chat/config/OpenApiConfig.java
- spring-chatting-backend-server/src/main/java/chatting/chat/config/RabbitMQConfig.java
- spring-chatting-backend-server/src/main/java/chatting/chat/config/WebConfig.java
- spring-chatting-backend-server/src/main/java/chatting/chat/web/ChatController.java
- spring-chatting-backend-server/src/main/resources/application.yaml
- spring-chatting-front-server/src/main/java/chatting/chat/web/filters/WebConfig.java
- spring-chatting-front-server/src/main/java/chatting/chat/web/filters/filter/LoginCheckFilter.java
- spring-chatting-front-server/src/main/java/chatting/chat/web/login/LoginController.java
- spring-chatting-front-server/src/main/resources/templates/login/loginForm.html
* **Add Swagger-ui for api docs**
* **Extract RabbitMQ in docker-compose-only-chat.yaml which is not using any of those MQ(Rabbit, Kafka)**
> [dev] limit logs, add swagger api docs with details

- docker-compose-only-chat.yaml
- only-chat-run.sh
- spring-chatting-backend-server/src/main/java/chatting/chat/web/ChatController.java
- spring-chatting-backend-server/src/main/java/chatting/chat/web/dto/RequestUser.java
- spring-chatting-backend-server/src/main/resources/application.yaml
- spring-chatting-front-server/src/main/java/chatting/chat/web/filters/WebConfig.java
- spring-chatting-front-server/src/main/java/chatting/chat/web/filters/filter/LoginCheckFilter.java
- spring-chatting-front-server/src/main/java/chatting/chat/web/login/LoginController.java
- spring-chatting-front-server/src/main/java/chatting/chat/web/login/dto/LoginRequestDto.java
- spring-chatting-front-server/src/main/java/chatting/chat/web/login/dto/LoginResponseDto.java
- spring-chatting-front-server/src/main/java/chatting/chat/web/user/UserController.java
- spring-chatting-front-server/src/main/java/chatting/chat/web/user/dto/RequestUser.java
- spring-chatting-front-server/src/main/resources/templates/login/loginForm.html
- spring-chatting-front-server/src/main/resources/templates/users/addUserFormSingle.html
+ add bash script for running chatting servers
> [fix] #52, change DTO, ignore original loginCheckFilter

- .github/workflows/deploy.yaml
> [patch] fix scp error

- .github/workflows/deploy.yaml
[patch] rewrite path of ec2 access key
> [patch] rewrite path of ec2 access key

- .github/workflows/deploy.yaml
- run.sh
[patch] edit path of server project
> [patch] edit path of server project

- .github/workflows/deploy.yaml
* removing connection between build and deploy action
> [patch] removing connection between build and deploy action

- customer-service/src/main/java/com/example/orderservice/kafka/KafkaTopicConfig.java
- customer-service/src/main/resources/application.yaml
- customer-service/src/main/resources/bootstrap.yaml
- shop-user-service/src/main/java/com/example/shopuserservice/web/kafka/KafkaTopicConfig.java
- shop-user-service/src/main/resources/application.yaml
- shop-user-service/src/main/resources/bootstrap.yaml
- spring-chatting-backend-server/src/main/java/chatting/chat/web/kafka/KafkaTopicConfig.java
- spring-chatting-backend-server/src/main/resources/application.yaml
* Close #98 
* Re-setting broker number in `user-service`, `customer-server`, `chat-service` with injection from application.yaml
> 3 brokers to 1 broker
> Re-setting broker number in user-service, customer-server, chat-service

- docker-compose-prod.yaml
- push_to_ecr.sh
* Close #103 
* Adding build in `docker-compose-prod.yaml`
For example, we add `build` and set context, file path in every services.
```yaml
configuration-server:
...
build:
context: ./config-service
dockerfile: Dockerfile
image: configuration-server:latest
...
> [patch] add docker compose build path

- .github/workflows/deploy.yaml
* Relate #107 
* edit `ecr_url` with ${secrets.ECR_URL}
```yaml
- name: Login to Amazon ECR
id: login-ecr
uses: aws-actions/amazon-ecr-login@v1
- name: Grant execute permission for push_to_ecr.sh
run: chmod +x ./push_to_ecr.sh
- name: Tag Push images to ECR
env:
ECR_URL: ${{ secrets.ECR_URL }}
run: ./push_to_ecr.sh ${ECR_URL} ${{ env.NEW_VERSION }}
```
> [patch] ECR_URL changed

- .github/workflows/deploy.yaml
* Close #108 
* Rewrite path to ECR URL
> [dev] ECR URL environment setting

- run.sh
* Close #111 
* Add `main-service_` prefix for pulled images from ECR
> [patch] add main-service_ prefix

- .github/workflows/chat-only.yaml
- k8s/onlychat/deployment/chatting-server-deployment.yaml
- k8s/onlychat/deployment/write_image_to_deploy.sh
* Removing image name prefix
* Rewrite kubernetes configuration path
> [patch] removing image name prefix, edit sh in workflow

- .github/workflows/chat-only.yaml
- k8s/onlychat/deployment/write_image_to_deploy.sh
* Edit new tagging logics! Finally works
* K8S DB voluem added
> [patch] Test/only chat cicd

- k8s/onlychat/deployment/pgadmin-deployment.yaml
- k8s/onlychat/service/pgadmin-service.yaml
- k8s/onlychat/volume/pgdata-chatpersistentvolume.yaml
- remove_dangling_image.sh
* Related #127 
* Implement PV configuring
* Mounting right path
> [patch] Kubernetes Configuring Process

- .github/workflows/deploy.yaml
- .github/workflows/testing.yml
* rewrite `AWS_SECRET_ACCESS_KEY`
> [fix] change AWS_SECRET_ACCESS_KEY

- .github/workflows/deploy.yaml
- k8s/onlychat/deployment/user-server-deployment.yaml
- k8s/onlychat/redis.yaml
* kubectl applying redis.yaml
* edit configMap and Pod setting in redis.yaml
> [dev] edit redis pod&configmap settings

- k8s/onlychat/deployment/api-server-deployment.yaml
- k8s/onlychat/deployment/chatting-server-deployment.yaml
- k8s/onlychat/deployment/customer-server-deployment.yaml
- k8s/onlychat/deployment/discovery-server-deployment.yaml
- k8s/onlychat/deployment/front-server-deployment.yaml
- k8s/onlychat/deployment/user-server-deployment.yaml
- k8s/onlychat/deployment/zookeeper-deployment.yaml
* match `spec.selector.matchLabels` with `template.metadata.labels`
> [fix] template.metadata.labels unmatch with spec.selector

- k8s/onlychat/deployment/customer-server-deployment.yaml
- k8s/onlychat/service/customer-db-service.yaml
- k8s/onlychat/service/user-db-service.yaml
* remove unsupported ports.port in deployment.yaml
* customer-server-deployment.yaml
* set all db's service name without `-service` postfix
> [fix] remove unsupported ports.port in deployment

- k8s/onlychat/deployment/kafka1-deployment.yaml
* remove field of ports in kafka-deployment.yaml
> [fix] removing kafka broker unsupported ports field

- k8s/onlychat/ecr-registry-token-refresh.yaml
* k8s batch version change `batch/v1beta1` to `batch/v1`
> [fix] k8s batch version change

- k8s/onlychat/ecr-registry-token-refresh.yaml
* docker login token redirection
> [fix] aws-cli bashscript

- k8s/onlychat/deployment/chat-db-deployment.yaml
- k8s/onlychat/deployment/chatting-server-deployment.yaml
- k8s/onlychat/deployment/customer-db-deployment.yaml
- k8s/onlychat/deployment/customer-server-deployment.yaml
- k8s/onlychat/deployment/pgadmin-deployment.yaml
- k8s/onlychat/deployment/user-db-deployment.yaml
- k8s/onlychat/deployment/user-server-deployment.yaml
- k8s/onlychat/ecr-cred-updater.sh
- k8s/onlychat/ecr-registry-token-refresh.yaml
- k8s/onlychat/service/chat-db-service.yaml
- k8s/onlychat/service/customer-db-service.yaml
- k8s/onlychat/service/user-db-service.yaml
* Related #180 
* Hiding all db secrets inside Kubernetes secret
* Add ecr-cred-updater for `CronJob`, but not done yet
* Edit port name that isn't proper naming
> [dev] Hiding db secrets #180

- .github/workflows/deploy.yaml
* Fix Git Workflow job naming syntax
> [fix] git workflow job naming syntax

- .github/workflows/deploy.yaml
> [fix] job naming syntax

- .github/workflows/deploy.yaml
* Debugging https://github.com/ghkdqhrbals/spring-chatting-server/actions/runs/6919067574 for ignore if syntax of getting PR.title
> [chore] debuging for if syntax

- .github/workflows/deploy.yaml
* Add cloning code steps inside `push image to AWS-ECR` job
> [dev] add checkout code in build jobs

- .github/workflows/deploy.yaml
* Fix wrong syntax of `steps.with`
> [fix] syntax workflow _with_

- .github/workflows/deploy.yaml
* removing unused options slack alert
> [fix] Slack alert

- .github/workflows/deploy.yaml
* move `NEW_VERSION` environment import inside steps
* move `pushToSlack` job to the end of workflow
> [fix] new_version,ecr_url enviroment import inside steps

- .github/workflows/deploy.yaml
* move env setting inside `pushImageToEcr` job
> [fix] Debug NEW_VERSION import part

- .github/workflows/deploy.yaml
* Debugging sharable variables that `new_verison`
> [fix] looging job sharable variables

- .github/workflows/deploy.yaml
* Trace `NEW_VERIOSN` shared variable
> [fix] trace new_version shared variable

- .github/workflows/deploy.yaml
* removing unused echo script
* change `${NEW_VERSION}` to `${new_version}`
> [fix] slight change ${NEW_VERSION} to ${new_version}

- .github/workflows/deploy.yaml
* Removing `... >> $GITHUB_ENV` which makes env in secret(I assumed)
> [fix] removing >> $GITHUB_ENV

- .github/workflows/deploy.yaml
* `$GITHUB_ENV` -> `$GITHUB_OUTPUT`
> [fix] change with $GITHUB_OUTPUT

- .github/workflows/deploy.yaml
* Removing all debug code
* **Now with `${{ needs.pushNewTag.outputs.NEW_VERSION }}` command, `NEW_VERSION` variable can be shared!**
> [fix] removing all old configuration and debug code

- .github/workflows/deploy.yaml
- README.md
* `env.NEW_VERSION` change to `steps.increment_version.outputs.NEW_VERSION`
> [fix] share other steps with output settings

- .github/workflows/deploy.yaml
* edit `secrets.ECR_UR` to `env.ECR_URL`. `secrets.etc` could be performed as  null inside ssh server so i changing that by using env
> [fix] edit secrets.ECR_URL to env.ECR_URL

- .github/workflows/deploy.yaml
* Add checkout for getting secrets
* Add `{ }` to `$ECR_URL`
> [fix] trace ECR_URL with secrets

- .github/workflows/deploy.yaml
* add reading secrets inside checkout code
* retrieve ecr_url in  ssh
> [fix] secrets add inside checkout code and retreive in ssh

- .github/workflows/deploy.yaml
* pass secret to ssh with`envs` field that supported [https://github.com/appleboy/ssh-action](https://github.com/appleboy/ssh-action)
> [fix] pass secret to ssh with ens field

- k8s/onlychat/deployment/write_image_to_deploy.sh
* Print all 3 parameters before exit script(If no param was observed, just print nothing)
> [fix] print all params before exit

- .github/workflows/deploy.yaml
* Passing ECR_URL to SSH with `envs`, `env` just like the reference [https://github.com/appleboy/ssh-action](https://github.com/appleboy/ssh-action)
> [fix] passing ECR_URL to SSH

- .github/workflows/deploy.yaml
* ssh version from `1.0.0` to `v1.0.0`
> [fix] correct mismatched ssh version

- .github/workflows/deploy.yaml
- k8s/onlychat/deployment/user-server-deployment.yaml
* Removing unused `GITHUB_OUTPUT`
* Add `"` to all env values
> [fix] db-password reset

- .github/workflows/deploy.yaml
* Add shared environment variables with `{ }`
> [fix] add {} to shared variable

- .github/workflows/deploy.yaml
* Revise wrong syntax of `env` setting
> [fix] correct syntax of env in applyboy ssh job

- .github/workflows/deploy.yaml
* relocate`env` setting outside of `with` field
> [fix] wrong syntax of env setting

- .github/workflows/deploy.yaml
* Removing all `{}` in bash script which is not right syntax
> [fix] removing {} inside bash script

- spring-chatting-backend-server/build.gradle
* Downgrade oTel to 1.22 and force it
> [fix] downgrade oTel to 1.22

- apigateway-service/Dockerfile
- config-service/Dockerfile
- customer-service/Dockerfile
- discovery/Dockerfile
- k8s/onlychat/deployment/chatting-server-deployment.yaml
- shop-user-service/Dockerfile
- shop-user-service/src/main/resources/application.yaml
- spring-chatting-backend-server/Dockerfile
- spring-chatting-backend-server/src/main/resources/application.yaml
- spring-chatting-front-server/Dockerfile
* add `prometeus enabled: true`
* change spring profile to `prod`
> [dev] spring profile setting and reset kafka url&port

- .github/workflows/deploy.yaml
- k8s/onlychat/deployment/api-server-deployment.yaml
- k8s/onlychat/deployment/chatting-server-deployment.yaml
- k8s/onlychat/deployment/customer-server-deployment.yaml
- k8s/onlychat/deployment/user-server-deployment.yaml
- k8s/onlychat/service/kafka1-service.yaml
- spring-chatting-backend-server/src/main/resources/application.yaml
* Temporary disable `ecr-registry-token-refresh` cronJob
* Change `kafka-broker` url
* Path rewrite api-server's RaabbitMQ url
> [fix] kafka address change

- .github/workflows/deploy.yaml
* Removing comment on `kubectl apply -f ecr-registry-token-refresh.yaml`
> [fix] removing comment on ecr-refresh

- apigateway-service/build.gradle
- apigateway-service/src/main/java/com/example/apigatewayservice/ApigatewayServiceApplication.java
- apigateway-service/src/main/resources/application.yaml
- discovery/build.gradle
* Change spring boot version to `3.1.5`
* Removing spring-cloud-kubernetes implementation
> [fix] Spring-boot v3.1.5 update

- k8s/onlychat/deployment/discovery-server-deployment.yaml
* Add reainessProbe & livenessProbe for Spring-Actuator
* Add resource setting for Spring Actuator's `processorMetrics` bean
> [fix] liveness&readinessProbe set

- discovery/src/main/resources/application.yaml
- k8s/onlychat/deployment/discovery-server-deployment.yaml
* Exposing all probes(health, etc.)
* Removing Probe yaml in deployment
> [fix] exposing all probes

- k8s/onlychat/deployment/discovery-server-deployment.yaml
* Fix wrong syntax of `discovery-deployment.yaml`
> [fix] deployment syntax

- k8s/onlychat/deployment/discovery-server-deployment.yaml
* Adding `-` for right deployment syntax
> [fix] deployment syntax correction

- .github/workflows/deploy.yaml
- discovery/src/main/resources/application.yaml
* Exclude actuator's metrics with beans, env
* Exclude un-used options of slack alert
> [fix] actuator exclude beans&env

- discovery/build.gradle
- k8s/onlychat/deployment/discovery-server-deployment.yaml
- k8s/onlychat/deployment/eureka.yaml
* Dependency management version change
* Temporary exclude discovery service
* Instead of custom discovery service image, get image from springcloud and deploy
> [fix] eureka server without spring modules

- apigateway-service/src/main/resources/application.yaml
- k8s/onlychat/deployment/api-server-deployment.yaml
* Write actual URL of EUREKA server
* DI serviceUrl
> [fix] eureka server url rewrite

- k8s/onlychat/deployment/chatting-server-deployment.yaml
- k8s/onlychat/deployment/customer-server-deployment.yaml
- k8s/onlychat/deployment/user-server-deployment.yaml
* Kafka url configuration redirection
> [dev] change kafka path in deploy.yaml

- k8s/onlychat/deployment/chatting-server-deployment.yaml
- k8s/onlychat/deployment/customer-server-deployment.yaml
- k8s/onlychat/deployment/user-server-deployment.yaml
* Single broker change to 3 broker that already define inside K8S with helm chart
> [fix] change kafka url path

- k8s/onlychat/deployment/chatting-server-deployment.yaml
- k8s/onlychat/deployment/customer-server-deployment.yaml
- k8s/onlychat/deployment/user-server-deployment.yaml
- spring-chatting-backend-server/src/main/java/chatting/chat/web/kafka/KafkaTopicConfig.java
> [fix] kafka url path change

- spring-chatting-backend-server/build.gradle
- spring-chatting-backend-server/src/main/java/chatting/chat/domain/user/api/UserController.java
- spring-chatting-backend-server/src/main/java/chatting/chat/domain/user/entity/User.java
- spring-chatting-backend-server/src/main/java/chatting/chat/domain/user/repository/UserRepository.java
- spring-chatting-backend-server/src/main/java/chatting/chat/domain/user/service/UserServiceImpl.java
- spring-chatting-backend-server/src/test/java/chatting/chat/Integration/Integration.java
- spring-chatting-backend-server/src/test/java/chatting/chat/domain/user/service/UserServiceTest.java
* Implement builder pattern to User entity
* `findByUserId` with Optional
* Using `findByUserId` with Optional `.orElseThrow()` methods
* Set initial test setting
> [dev] chatting-server code refactoring

- spring-chatting-backend-server/src/main/java/chatting/chat/web/kafka/KafkaAdminConfig.java
- spring-chatting-backend-server/src/main/java/chatting/chat/web/kafka/KafkaProducerConfig.java
* `@EnableKafka` Location change
> [fix] EnableKafka anotation location change

- k8s/onlychat/deployment/api-server-deployment.yaml
- k8s/onlychat/deployment/chatting-server-deployment.yaml
- k8s/onlychat/deployment/discovery-server-deployment.yaml
- k8s/onlychat/deployment/user-server-deployment.yaml
- k8s/onlychat/service/discovery-server-service.yaml
* EUREKA server deployed
* Change eureka url path
> [dev] EUREKA server added

- k8s/onlychat/deployment/chatting-server-deployment.yaml
- k8s/onlychat/deployment/kafka-deployment.yaml
> [fix] Resource reconfig

- .github/workflows/deploy.yaml
- k8s/onlychat/deployment/front-server-deployment.yaml
- k8s/onlychat/eks/aws-auth.yaml
- k8s/onlychat/eks/ingress.yaml
- k8s/onlychat/eks/issuer.yaml
- k8s/onlychat/service/front-server-service.yaml
* Add deployment jobs for eks
* AWS-Auth-verification added
* Implement Nginx-Ingress-Controller
* Implement letsencrypt auto issuer
> [minor] aws-eks cluster deployment

- .github/workflows/deploy.yaml
* checkout version change
* `write_image_to_deploy.sh` path redirect
> [minor] PR title echo and sh fixing

- k8s/onlychat/eks/aws-auth.yaml
* github-ci to github_actions user change
> [fix] AWS ConfigMap edit

- k8s/onlychat/volume/chat-pv.yaml
- k8s/onlychat/volume/customer-pv.yaml
- k8s/onlychat/volume/pgadmin-pv.yaml
- k8s/onlychat/volume/user-pv.yaml
> [dev] nfs server reconfig

- k8s/onlychat/volume/chat-pv.yaml
- k8s/onlychat/volume/chat-pvc.yaml
- k8s/onlychat/volume/customer-pv.yaml
- k8s/onlychat/volume/customer-pvc.yaml
- k8s/onlychat/volume/pgadmin-pv.yaml
- k8s/onlychat/volume/user-pv.yaml
- k8s/onlychat/volume/user-pvc.yaml
* Close #269 
* PV storage capacity upgrade
* Set storageClassName to empty string(Stop configured by AWS-EBS)
> [fix] #269 add empty string storageClass

- k8s/onlychat/deployment/api-server-deployment.yaml
- k8s/onlychat/deployment/user-server-deployment.yaml
- shop-user-service/build.gradle
* `43.202.52.177`(Public IPv4 EC2) to `43.203.25.44`(Elastic IP Address)
> [fix] Elastic IP set

- k8s/onlychat/deployment/user-server-deployment.yaml
- shop-user-service/build.gradle
* Change to `main-service_` prefixed image
* Add openfeign
> [fix] add openfeign

- apigateway-service/src/main/resources/application.yaml
* port number changed to `8010`
> [fix] wrong user server port number

- k8s/onlychat/deployment/chatting-server-deployment.yaml
- k8s/onlychat/deployment/user-server-deployment.yaml
- k8s/onlychat/redis.yaml
* Change redis url path `redis.default.svc.cluster.local` to `redis-service`
> [fix] #274 redis url redirection

- k8s/onlychat/deployment/chatting-server-deployment.yaml
- k8s/onlychat/deployment/user-server-deployment.yaml
* `spring_redis_host` -> `spring_data_redis_host`, and also port
> [fix] yaml path redis url change

- k8s/onlychat/eks/ingress.yaml
- k8s/onlychat/eks/issuer.yaml
- k8s/onlychat/service/front-server-service.yaml
- spring-chatting-front-server/src/main/java/chatting/chat/web/login/util/CookieUtil.java
- spring-chatting-front-server/src/main/resources/templates/chat/chats.html
* Close #274 
* Using letsencrypt for generate TLS certificates
* Implement cert-manager for automatically re issuing TLS certificates
* Hiding front-server's ip and port with `ClusterIP`
* Removing unused chat component
> [minor] nginx ingress issuer deployed

- k8s/onlychat/eks/ingress.yaml
- spring-chatting-front-server/src/main/resources/templates/chat/newChat.html
> [fix] cancle button click

- .github/workflows/deploy.yaml
- k8s/onlychat/eks/ingress.yaml
* Close #287 
* Workflow now trigger on pull request
> [minor] #287 workflow trigger on pr

- .github/workflows/deploy.yaml
- k8s/onlychat/eks/ingress.yaml
- shop-user-service/src/main/java/com/example/shopuserservice/web/security/ReactiveSecurityConfig.java
- shop-user-service/src/main/java/com/example/shopuserservice/web/security/filter/JwtTokenAuthenticationFilter.java
- shop-user-service/src/main/java/com/example/shopuserservice/web/security/token/util/TokenUtil.java
* Add access to /health-check and swagger
* Add some comments
> [fix] spring security config

- shop-user-service/build.gradle
- shop-user-service/src/main/java/com/example/shopuserservice/config/WebConfig.java
- shop-user-service/src/main/java/com/example/shopuserservice/web/logger/LoggingInterceptor.java
* Add webmvc for logging controller in and out
* Add Logging interceptor
> [dev] add Logging interceptor

- shop-user-service/src/main/java/com/example/shopuserservice/web/logger/LoggingInterceptor.java
- shop-user-service/src/main/java/com/example/shopuserservice/web/security/ReactiveSecurityConfig.java
- shop-user-service/src/main/java/com/example/shopuserservice/web/security/filter/JwtTokenAuthenticationFilter.java
* Edit logger
* Edit JWT filter logics
> [fix] accessToken varification

- k8s/onlychat/eks/ingress.yaml
* Close #293
* Change nginx ingress regex for rewrite path
> [fix] #293 url regex

- shop-user-service/src/main/java/com/example/shopuserservice/web/api/LoginController.java
- shop-user-service/src/main/java/com/example/shopuserservice/web/api/UserController.java
- shop-user-service/src/main/java/com/example/shopuserservice/web/security/LoginService.java
> [performance] .log() remove

- shop-user-service/src/main/resources/application.yaml
* Originally server has 4 io.threads and 64 worker.threads. Now update each threads with 16, 256
> [performance] update undertow threads

- shop-user-service/src/main/resources/application.yaml
* HikariCP TransactionPoolSize increase to 100
> [performance] increase hikaricp 30 to 100

- common-dto/src/main/java/com/example/commondto/dto/friend/FriendResponse.java
- spring-chatting-backend-server/src/main/java/chatting/chat/config/RedisConfig.java
* Caching manager update
* Use GenericJackson2JsonRedisSerializer for serialize
* 1 hour duration set
* DTO seriablizable
> [fix] caching Manager update

- spring-chatting-backend-server/src/main/java/chatting/chat/domain/friend/api/FriendController.java
- spring-chatting-backend-server/src/main/java/chatting/chat/domain/friend/service/FriendService.java
- spring-chatting-backend-server/src/main/java/chatting/chat/domain/friend/service/FriendServiceImpl.java
- spring-chatting-backend-server/src/main/java/chatting/chat/domain/user/service/UserServiceImpl.java
- spring-chatting-backend-server/src/main/resources/application.yaml
* Add friends will now remove friendsList cache.
* `open-in-view: false`
> [performance] cache remove process, http db connection maintain disable

- spring-chatting-backend-server/src/main/java/chatting/chat/domain/user/service/UserServiceImpl.java
- spring-chatting-backend-server/src/main/resources/application.yaml
> [performance] #308 un-used query delete

- spring-chatting-backend-server/src/main/java/chatting/chat/domain/user/service/UserServiceImpl.java
> [performance] undo cache

- k8s/onlychat/deployment/chatting-server-deployment.yaml
- k8s/onlychat/eks/external-grafana.yaml
- k8s/onlychat/eks/ingress.yaml
- k8s/onlychat/hpa/chatting-server-hpa.yaml
- spring-chatting-backend-server/src/main/java/chatting/chat/domain/user/service/UserServiceImpl.java
- spring-chatting-front-server/src/main/resources/application.yaml
* Add HorizontalPodAutoscaler for chatting-server min 1 to max 3 according to avg cpu usage of 50%
* Add Resource limit for chatting-server
> Autoscalable chatting-server Pods

- spring-chatting-backend-server/src/main/java/chatting/chat/web/filter/UserContextInterceptor.java
* Servlet 인터셉터 필터에 whiteList 구현
> [fix] whiteList add

- apigateway-service/build.gradle
- k8s/onlychat/hpa/chatting-server-hpa.yaml
- k8s/onlychat/monitoring/prometheus.yaml
- spring-chatting-backend-server/src/main/resources/application.yaml
* Chat HPA 스케일 다운 대기시간 30분으로 증가
* API gateway, chatting-server actuator 로 프로메테우스 매트릭 수집
> [dev] collect metrics of api, chat server

- spring-chatting-backend-server/src/main/resources/application.yaml
* 최대 스레드 생성 개수 : 10 -> 100
* 최소 실행 스레드 개수 : 10 -> 30
> [performance] tomcat max threads 증가 및 스페어 스레드 설정

- k8s/onlychat/service/discovery-server-service.yaml
- spring-chatting-backend-server/src/main/java/chatting/chat/config/Monitoring.java
- spring-chatting-backend-server/src/main/java/chatting/chat/config/WebConfig.java
* Spring Discovery 서버 LB 노출 제거
* 모니터링 메트릭 추가
> [dev] spring boot 모니터링을 위한 micrometer 설정

- spring-chatting-backend-server/src/main/java/chatting/chat/web/filter/UserContextInterceptor.java
* Interceptor 에서 URI whitelist 인지 체크 시 stream null 오류 수정
> [fix] interceptor URI whitelist validation

- spring-chatting-backend-server/src/main/java/chatting/chat/config/TimedConfiguration.java
* `@Timed` 어노테이션을 사용하기 위한 Micrometer 빈 등록
> [dev] micrometer @timed configuration

- .gitignore
- common-dto/src/main/java/com/example/commondto/dto/participant/ParticipantRequest.java
- spring-chatting-backend-server/build.gradle
- spring-chatting-backend-server/src/main/java/chatting/chat/config/JpaConfig.java
- spring-chatting-backend-server/src/main/java/chatting/chat/domain/participant/api/ParticipantController.java
- spring-chatting-backend-server/src/main/java/chatting/chat/domain/participant/service/ParticipantService.java
- spring-chatting-backend-server/src/main/java/chatting/chat/domain/participant/service/ParticipantServiceImpl.java
- spring-chatting-backend-server/src/main/java/chatting/chat/web/filter/UserContextInterceptor.java
- spring-chatting-backend-server/src/test/java/chatting/chat/domain/participant/api/ParticipantControllerTest.java
- spring-chatting-backend-server/src/test/java/chatting/chat/domain/participant/service/ParticipantServiceImplTest.java
* 채팅방 CRUD 구현
* 해당 기능 Test 추가
* 라인 coverage 확인 기능 추가
> [patch] 채팅방 CRUD 기능 추가 및 Test

- spring-chatting-backend-server/src/main/resources/application.yaml
* Lettuce CP(Connection Pool) 설정
* max-active = 8(default) -> 100
* max-idle = 8(default) -> 50
* min-idle = 0(default) -> 10
> [performance] lettuce cp 설정

- spring-chatting-backend-server/src/main/resources/application.yaml
* max-active = 100 -> 150 (tomcat thread 에 맞춰 증량)
* max-idle = 50 -> 70 최대한 많이 유지되도록 증량
* min-idle = 10 -> 50 최대한 많이 유지되도록 증량
> [performance] lettuce pool 수정

- spring-chatting-backend-server/build.gradle
- spring-chatting-backend-server/src/main/java/chatting/chat/web/filter/UserContextInterceptor.java
- spring-chatting-backend-server/src/main/java/chatting/chat/web/token/JwtTokenValidator.java
* 채팅서버에 jwt validation 로직 추가 및 secret config actuator bus 설정
> [dev] accessToken 활용 로직 추가

- spring-chatting-front-server/src/main/resources/templates/chat/chat.html
- spring-chatting-front-server/src/main/resources/templates/chat/chats.html
* 채팅이 동일 시간이라면 최초 한번만 출력
* 채팅 사용자 이름 출력 구현
> [dev] chat 상대방 사용자 이름 확인기능

- k8s/onlychat/deployment/chat-db-deployment.yaml
- k8s/onlychat/deployment/user-db-deployment.yaml
* k8s `resources` field context error fix
> [fix] db resource context error

- spring-chatting-backend-server/src/main/java/chatting/chat/domain/user/service/UserServiceImpl.java
- spring-chatting-backend-server/src/test/java/chatting/chat/domain/user/service/UserServiceImplTest.java
> [fix] 테스트코드 수정

- spring-chatting-backend-server/src/main/java/chatting/chat/domain/user/service/UserServiceImpl.java
- spring-chatting-backend-server/src/test/java/chatting/chat/domain/room/service/RoomServiceImplTest.java
* 채팅방 추가 시, 캐시 업데이트를 Write-Around 정책으로 수정
> [fix] 캐시 Evict 정책 추가

- spring-chatting-backend-server/src/main/resources/application.yaml
> [dev] reset tomcat config

- .github/workflows/deploy.yaml
- k8s/onlychat/configmap/chat-db-configmap.yaml
- k8s/onlychat/deployment/chat-db-deployment.yaml
- k8s/onlychat/deployment/chatting-server-deployment.yaml
- spring-chatting-backend-server/src/main/resources/application.yaml
* Postgresql ConfigMap 설정
* Postgresql MaxConnection 100 -> 300 증가
> 낮은 row 로 인한 select 쿼리 cpu 사용량이 매우 낮기 때문에 증가해도 괜찮다고 생각합니다
* DB 병렬 스레드 설정
* Slack Alert 수정
* HikariCP 사이즈를 maxConnection 개수에 맞춰 설정. 100 conn * 3개 파드 = 300 conn(max-connection)
> [dev] configmap 설정 및 psql max connection, CP 증가

- k8s/onlychat/deployment/chatting-server-deployment.yaml
* 다른 클라이언트를 위해 connection 여유를 남겼습니다.
> [fix] maxconnection remaining

- .github/workflows/deploy.yaml
- k8s/onlychat/configmap/chat-db-configmap.yaml
- k8s/onlychat/deployment/chat-db-deployment.yaml
- k8s/onlychat/hpa/chatting-server-hpa.yaml
* HPA min pod size 3->1
* Postgresql 중복 볼륨 참조로 인한 configmap 제거 
* Slack 알림 link 추가
> [fix] Postgresql 세부 설정 args -c 옵션 추가

- k8s/onlychat/deployment/chat-db-deployment.yaml
- k8s/onlychat/deployment/chatting-server-deployment.yaml
- spring-chatting-backend-server/src/test/resources/application.yaml
* Tomcat max-NIO thread syntax change
> [performance] Tomcat thread, DB conn, CP optimizing

- shop-user-service/src/main/java/com/example/shopuserservice/domain/user/data/User.java
- shop-user-service/src/main/java/com/example/shopuserservice/domain/user/data/util/ToEntity.java
- shop-user-service/src/main/java/com/example/shopuserservice/domain/user/service/UserCommandQueryService.java
- shop-user-service/src/main/java/com/example/shopuserservice/domain/user/service/UserCommandQueryServiceImpl.java
- shop-user-service/src/main/java/com/example/shopuserservice/domain/user/service/modules/UserRedisManager.java
- shop-user-service/src/main/java/com/example/shopuserservice/domain/user/service/reactor/UserStatusManager.java
- shop-user-service/src/main/java/com/example/shopuserservice/web/api/UserController.java
- shop-user-service/src/main/java/com/example/shopuserservice/web/util/reactor/Reactor.java
- shop-user-service/src/main/resources/application.yaml
* UserEntity 변환 유틸 추가
* 주석 추가 및 리팩토링
> [dev] 주석처리 및 리팩토링

- .github/workflows/deploy.yaml
- .github/workflows/pr-alert.yaml
- k8s/onlychat/hpa/chatting-server-hpa.yaml
* reducing chat max pods to 2
* switch eks to gke, cause of the costs
* add pr-comment workflow
> [minor] EKS change to GKE ( aws -> google cloud )
